### ISSUE TITLE
Ray Queries from 'VK_KHR_ray_tracing'

### ISSUE THREAD

**Issue by helixd-2k18** [GraphicsProgramming/RVPT#25]
I would suggest not to bother with the Ray-Tracing (rgen, rchit, rmiss) shader, but go straight to compute shaders with Ray Query. Moreover, I would suggest it rather as an option…

**Comment by charles-lunarg** [comment]
Currently, RVPT only uses compute shaders and doesn't require the VK_KHR_ray_tracing extension to operate.

**Comment by nickclark2016** [comment]
Closing issue, as this is irrelevant.

**Comment by cdgiessen** [comment]
RVPT uses compute shaders already.
