### ISSUE TITLE
window resize

### ISSUE THREAD

**Issue by tigrazone** [GraphicsProgramming/RVPT#66]
when I trying to resize window, program fails.
How to implement window resize?

**Comment by cdgiessen** [comment]
Basically you need to recreate the swapchain whenever a resize event occurs.

https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation

Also some more details about doing it with more of an eye towards smoothness

https://gist.github.com/nanokatze/bb03a486571e13a7b6a8709368bd87cf#file-handling-window-resize-md

**Comment by cdgiessen** [comment]
I forgot to state that I believe RVPT doesn't support resizing at the moment. So my linking of the tutorial is a way of saying "its hard to explain, here is a better resource on how to do it."
